### ISSUE TITLE
cross-region-replication is available for SSE-KMS

### ISSUE THREAD

**Issue by vgallissot** [BWITS/terraform-state-bucket#1]
CF link you propose: https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-what-is-isnot-replicated.html
> In addition to unencrypted objects, Amazon S3 replicates objects encrypted using Amazon S3 managed keys (SSE-S3) or AWS KMS managed keys (SSE-KMS). The replicated copy of the object is also encrypted using the same type of server-side encryption that was used for the source object, SSE-S3, or SSE-KMS. For more information about server-side encryption. see Protecting Data Using Server-Side Encryption. 

One could use SSE-KMS as well to encrypt its tfstate files.

**Comment by ozbillwang** [comment]
Thanks, seems the document was updated recently

https://github.com/awsdocs/amazon-s3-developer-guide/commits/master/doc_source/crr-what-is-isnot-replicated.md
